services:
  - type: web
    name: sticker-chatgpt-app
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: STICKER_ACCESS_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
